apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: w2app-config
    files:
      - config.yaml

# 可选：给所有资源统一加前缀、命名空间
# namePrefix: dev-
namespace: my-app

# 给所有资源统一加标签
labels:
  - pairs:
      app: w2app
    includeSelectors: true
    includeTemplates: true
