apiVersion: v1
kind: Service
metadata:
  name: w2-app-service
spec:
  type: NodePort
  selector:
    app: w2app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: http
      nodePort: 30885
